package com.jobtrackr.backend.entity.enums;

public enum SourceType {
    LINKEDIN,
    INDEED,
    GLASSDOOR,
    MONSTER,
    ZIPRECRUITER,
    GREENHOUSE,
    LEVER,
    WORKDAY,
    SMARTRECRUITERS,
    CAREERBUILDER,
    JOOBLE,
    ADZUNA,
    LINKUP,
    GOOGLE_JOBS,
    REMOTEOK,
    WEWORKREMOTELY,
    FLEXJOBS,
    HIMALAYAS,
    ANGELLIST,
    WELLFOUND,
    HN_WHOS_HIRING,
    STACKOVERFLOW_JOBS,
    GITHUB_JOBS,
    GETONBOARD,
    COMPUTRABAJO,
    BUMERAN,
    OCCMUNDIAL,
    INFOJOBS,
    EUROPE_LANGUAGE_JOBS,
    FACEBOOK_GROUP,
    X_TWITTER,
    COMPANY_WEBSITE,
    REFERRAL,
    RECRUITER_AGENCY,
    OTHER
}



